// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_index: dynamic(() => import("./ContentIndex")),
  hero: dynamic(() => import("./Hero")),
  hero_services: dynamic(() => import("./HeroServices")),
  image: dynamic(() => import("./Image")),
  text_block: dynamic(() => import("./TextBlock")),
  text_with_features: dynamic(() => import("./TextWithFeatures")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
